// WS: Fichier pour les constantes et l'état global du jeu

const GAME_WIDTH = 2560;
const GAME_HEIGHT = 1440;

let gameState = {
    currentScreen: 'main-menu',
    gameMode: 'survivor',
    isGameRunning: false,
    isPaused: false,
    isGameOver: false,
    isMusicOn: true,
    isSoundOn: true,
    player: null,
    enemies: [],
    projectiles: [],
    xpOrbs: [],
    pickups: [],
    particles: [],
    floatingTexts: [],
    entities: [],
    camera: { x: 0, y: 0, zoom: 1 },
    money: 0,
    wave: 0,
    killCount: 0,
    gameTime: 0,
    lastTime: 0,
    deltaTime: 0,
    selectedChar: 'MVX',
    selectedMap: 'classic',
    skillPoints: 0,
    upgrades: {},
    army: [],
    isSpectating: false,
    spectatingPlayerId: null,
    isJoystickActive: false,
    joystickStart: { x: 0, y: 0 },
    joystickCurrent: { x: 0, y: 0 },
    lastScreenWidth: window.innerWidth,
    lastScreenHeight: window.innerHeight,
    isSidePanelCollapsed: { army: true, upgrade: true },
    pentagramCharge: 0,
    pentagramMaxCharge: 100,
    isPentagramCharging: false,
    bonus: null,
};
